language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g tiddlywiki
script: 
  - tiddlywiki --load ./wiki ./wiki_example.html
  - tiddlywiki ./wiki --build

after_success:
  - bash ./publish.sh

branches:
  only:
    - master
    - /feature.*/